# Generated by Django 5.2.1 on 2025-05-28 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                (
                    "nav_title",
                    models.CharField(max_length=30, verbose_name="Название в меню"),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="Приоритет")),
                ("content", models.TextField(verbose_name="Контент")),
                (
                    "show_in_nav",
                    models.BooleanField(default=True, verbose_name="Показывать в меню"),
                ),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("me", "Я"),
                            ("leader", "Руководитель"),
                            ("manager", "Менеджер"),
                            ("classmate", "Сокурсник"),
                        ],
                        max_length=10,
                        verbose_name="Роль",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ФИО")),
                ("photo", models.ImageField(upload_to="photos/", verbose_name="Фото")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True, upload_to="resumes/", verbose_name="Резюме"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.page"
                    ),
                ),
            ],
            options={
                "verbose_name": "Персона",
                "verbose_name_plural": "Персоны",
            },
        ),
    ]
